account/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.indexUser, name='index_user'),
    url(r'^alterar-dados/$', views.updateUser, name='update_user'),
    url(r'^alterar-senha/$', views.updateUserPassword, name='update_password'),
    url(r'^criar/', views.createUser, name='create_user'),
]

core/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index')
]

topicos_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^entrar/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', logout, {'next_page': 'account:index_user'}, name='logout'),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^conta/', include('account.urls', namespace='account')),
    url(r'^evento/', include('events.urls', namespace='events')),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'indexcore.html')

core/templates/indexcore.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'account:index_user' %}">modulo de usuario</a>
{% endblock content %}

core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Entrar{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                {% for field in form %}
                    <div class="form-group{% if field.errors %} has-error{% endif %}">
                        <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
                        <div class="col-md-9">
                            {% render_field field class="form-control" %}
                            {% for error in field.errors %}
                            <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-4 col-md-offset-3">
                            <button type="submit" class="btn btn-primary form-control">Entrar</button>
                        </div>
                        <div class="col-md-4">
                            <a href="{% url 'account:create_user' %}" class="btn btn-primary form-control">Cadastrar</a> 
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock content %}